### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by Yogho358** [shiftleino/golf-course-app#1]
Sovellus toimii Herokussa hyvin ja dokumentoinnin mukaan, paitsi yhden virheen löysin. Kun lisäsin radan ja sitten lisäsin sille hinnan, rataluettolossa sen hintana pysyi None, enkä saanut sitä päivittymään.

Sitten pari asiaa, jotka eivät ole virheitä, mutta mielestäni hieman kömpelöitä:

Kun tekstikenttin yrittää syöttää virheellistä tekstiä, tai esim. yrittää rekisteröidä jo olemassaolevan käyttäjänimen, sovellus toimii oikein, eli ei hyväksy syötettä, mutta se ei anna käyttäjälle palautetta mikä meni vikaan.

Ratojen sorttaus on mielestäni hieman kömpelöä, itse ainakin yritin ensin luontaisesti tehdä sen klikkailemalla sarakkeiden otsitkoita ennenkuin huomasin napit.

Koodi on selkeää ja helposti muokattavaa, ainoan refaktorointimahdollisuuden huomasin siinä, että golf_coursesin get_basic_info:ssa on toisteista koodia if-else -rakenteessa.

**Comment by shiftleino** [comment]
Bugit korjattu, kiitos!
