### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by susannakinnunen** [shiftleino/golf-course-app#2]
Hieno, toimiva sovellus! Ulkoasu on tyylikäs ja käyttöliittymä miellyttävä.

Koodi oli selkeää ja se on jaettu järkevästi eri moduuleihin. Myös tietokanta oli siisti.
 
En itse huomannut mitään tietoturvaan liittyviä ongelmia.

Tässä muutama seikka, jotka tulivat mieleeni sovellusta testatessani:

### **Sign Up**

Salasanakenttiä voisi olla kaksi kappaletta, joista toinen tarkistaa, että molemmissa kentissä salasanat ovat samat. Näin käyttäjä voi varmistaa, että salasanaksi tulee juuri se, mikä oli tarkoituskin.

Kun on rekisteröitynyt, niin voisiko siitä tulla jokin ilmoitus? Ja ehkä samalla jo kirjautua sisään?

### **Admin**

**Kentän lisäys:**
Laitoin kenttiin mitä sattuu, esim. paikkakunnaksi kirjoitin Kuusamo ja kohtaan distance from Helsinki kirjoitin "monta sataa kilometriä". Nämä aiheuttivat Internal Server Errorin.

Kun jotkin kentät eivät olleet täytettyinä, niin ilmoitukseksi tuli "Something went wrong". Voiko ilmoitus olla tarkempi?

Lisäsin feikkikentän Kuusamosta Kuusamon koordinaateilla ja postiosoitteilla ja se meni läpi. Pystyykö tätä estämään, esimerkiksi määrittämällä tietyt koordinaatit raja-arvoiksi?

**Kaiken kaikkiaan, todella hyvää työtä!**

**Comment by shiftleino** [comment]
Toiminnallisuuksia lisätty, kiitos!
